import { Inter } from 'next/font/google'

import { Providers } from './providers'

import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers className={inter.className}>{children}</Providers>
      </body>
    </html>
  )
}
